/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAgentsRouteImport } from './routes/_app/agents'
import { Route as AppBrainRouteImport } from './routes/_app/brain'
import { Route as AppContentRouteImport } from './routes/_app/content'
import { Route as AppCreativeRouteImport } from './routes/_app/creative'
import { Route as AppOutboundRouteImport } from './routes/_app/outbound'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppTruthRouteImport } from './routes/_app/truth'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppBrainRoute = AppBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)
const AppCreativeRoute = AppCreativeRouteImport.update({
  id: '/creative',
  path: '/creative',
  getParentRoute: () => AppRoute,
} as any)
const AppOutboundRoute = AppOutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppTruthRoute = AppTruthRouteImport.update({
  id: '/truth',
  path: '/truth',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agents': typeof AppAgentsRoute
  '/brain': typeof AppBrainRoute
  '/content': typeof AppContentRoute
  '/creative': typeof AppCreativeRoute
  '/outbound': typeof AppOutboundRoute
  '/search': typeof AppSearchRoute
  '/truth': typeof AppTruthRoute
}
export interface FileRoutesByTo {
  '/agents': typeof AppAgentsRoute
  '/brain': typeof AppBrainRoute
  '/content': typeof AppContentRoute
  '/creative': typeof AppCreativeRoute
  '/outbound': typeof AppOutboundRoute
  '/search': typeof AppSearchRoute
  '/truth': typeof AppTruthRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/agents': typeof AppAgentsRoute
  '/_app/brain': typeof AppBrainRoute
  '/_app/content': typeof AppContentRoute
  '/_app/creative': typeof AppCreativeRoute
  '/_app/outbound': typeof AppOutboundRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/truth': typeof AppTruthRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/brain'
    | '/content'
    | '/creative'
    | '/outbound'
    | '/search'
    | '/truth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agents'
    | '/brain'
    | '/content'
    | '/creative'
    | '/outbound'
    | '/search'
    | '/truth'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/agents'
    | '/_app/brain'
    | '/_app/content'
    | '/_app/creative'
    | '/_app/outbound'
    | '/_app/search'
    | '/_app/truth'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brain': {
      id: '/_app/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof AppBrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content': {
      id: '/_app/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creative': {
      id: '/_app/creative'
      path: '/creative'
      fullPath: '/creative'
      preLoaderRoute: typeof AppCreativeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outbound': {
      id: '/_app/outbound'
      path: '/outbound'
      fullPath: '/outbound'
      preLoaderRoute: typeof AppOutboundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/truth': {
      id: '/_app/truth'
      path: '/truth'
      fullPath: '/truth'
      preLoaderRoute: typeof AppTruthRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppBrainRoute: typeof AppBrainRoute
  AppContentRoute: typeof AppContentRoute
  AppCreativeRoute: typeof AppCreativeRoute
  AppOutboundRoute: typeof AppOutboundRoute
  AppSearchRoute: typeof AppSearchRoute
  AppTruthRoute: typeof AppTruthRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppBrainRoute: AppBrainRoute,
  AppContentRoute: AppContentRoute,
  AppCreativeRoute: AppCreativeRoute,
  AppOutboundRoute: AppOutboundRoute,
  AppSearchRoute: AppSearchRoute,
  AppTruthRoute: AppTruthRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
